# -*- coding: utf-8 -*-
"""Screen catalyst.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tgPiIrafFUAdtDil1Tlu5VmS_f1aMSzO
"""

# ============================================================
# High-Throughput Electrocatalyst Screening
# Selective Methane-to-Methanol Upgrading via Electrochemical Oxidation
# Google Colab | mp-api + pymatgen
# ============================================================

# ============================================================
# 0. Install Dependencies
# ============================================================
# Pin pandas and requests to match Google Colab bounds while upgrading materials science packages
!pip install --upgrade pyarrow mp-api mpcontribs-client pymatgen boltons "numpy<2.1" -q
!pip install pandas==2.2.2 requests==2.32.4 --no-deps --force-reinstall -q

# ============================================================
# 1. Imports
# ============================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import warnings
warnings.filterwarnings("ignore")

from mp_api.client import MPRester
from pymatgen.analysis.pourbaix_diagram import PourbaixDiagram, PourbaixPlotter, PourbaixEntry

# Universal integration helper (supports both NumPy 1.x and 2.x)
def _trapz(y, x):
    if hasattr(np, "trapezoid"):
        return np.trapezoid(y, x)
    return np.trapz(y, x)

# ============================================================
# 2. USER INPUT PARAMETERS
# ============================================================
MP_API_KEY      = "VhG42T1WDDotMqdqcbId4MJGJVblvtgP"   # <-- paste your key

metal_symbol    = "Pt"          # Target transition metal
E_RHE           = 1.5           # Applied potential vs. RHE (V)
pH              = 10.0           # Electrolyte pH
temp_k          = 298.15        # Temperature (K)
ion_conc        = 1e-6          # Ion concentration (mol/L)

# Fixed reference energy levels (vacuum scale, eV)
E_SHE_abs       = -4.44         # Absolute SHE potential (eV vs. vacuum) [Trasatti convention]
E_HOMO_CH4      = -12.80        # CH4 HOMO level (eV vs. vacuum)
E_HOMO_CH3OH    = -10.00        # CH3OH HOMO level (eV vs. vacuum)

# ============================================================
# 3. UNIT CONVERSION: E_RHE → E_SHE
#    E_SHE = E_RHE - 0.05916 * pH   (at 298.15 K)
#    Note: Pourbaix diagrams use V vs. SHE
# ============================================================
E_SHE = E_RHE - 0.05916 * pH
print(f"[Unit Conversion] E_RHE = {E_RHE:.3f} V  →  E_SHE = {E_SHE:.4f} V  (pH={pH})")

# ============================================================
# 4. Operando Phase Stability — Pourbaix Analysis
# ============================================================
print("\n" + "="*60)
print("STEP 1: Pourbaix Phase Stability Diagnosis")
print("="*60)

with MPRester(MP_API_KEY) as mpr:
    pbx_entries = mpr.get_pourbaix_entries([metal_symbol])
    pbx = PourbaixDiagram(pbx_entries, conc_dict={metal_symbol: ion_conc}, filter_solids=True)

    # FIX: correct argument order is (pH, V) -- NOT (V, pH)
    stable_entry = pbx.get_stable_entry(pH, E_SHE)
    stable_formula = stable_entry.name

    stable_entry_id = None
    if hasattr(stable_entry, "entry") and hasattr(stable_entry.entry, "entry_id"):
        stable_entry_id = stable_entry.entry.entry_id
    elif hasattr(stable_entry, "entry_id"):
        stable_entry_id = stable_entry.entry_id
    if stable_entry_id is None:
        stable_entry_id = "ionic/unknown"

    print(f"  Metal Symbol       : {metal_symbol}")
    print(f"  E_SHE (operational): {E_SHE:.4f} V")
    print(f"  pH                 : {pH}")
    print(f"  Stable Phase       : {stable_formula}")
    print(f"  mp-id              : {stable_entry_id}")

    fig_pbx, ax_pbx = plt.subplots(figsize=(7, 5))
    plotter = PourbaixPlotter(pbx)
    plotter.get_pourbaix_plot(limits=[[-2, 16], [-3, 3]], ax=ax_pbx)
    ax_pbx.scatter([pH], [E_SHE], color='red', zorder=5, s=80,
                   label=f"Operating point\n(pH={pH}, {E_SHE:.2f} V)")
    ax_pbx.legend(fontsize=9)
    ax_pbx.set_title(f"Pourbaix Diagram — {metal_symbol} system")
    plt.tight_layout()
    plt.savefig("pourbaix_diagram.png", dpi=150)
    plt.show()

# ============================================================
# Cell 5: STEP 2 - Absolute Energy Alignment
# ============================================================
import time
from pymatgen.core import Element
from pymatgen.electronic_structure.core import OrbitalType

print("\n" + "="*60)
print("STEP 2: Electronic Structure & Absolute Energy Alignment")
print("="*60)

# ---- 2a. Active Fermi level (vacuum scale) ----
# CONFIRMED FIX: use pH-corrected E_SHE, NOT raw E_RHE
E_F_active = E_SHE_abs - E_SHE
print(f"  E_F,active = E_SHE_abs - E_SHE = {E_SHE_abs} - {E_SHE:.4f} = {E_F_active:.4f} eV")

# ---- 2b. Robust mp-id cleaning ----
def clean_mp_id(raw_id):
    """Return a clean 'mp-XXXX' string, or None if ionic/invalid."""
    if raw_id is None:
        return None
    raw_str = str(raw_id)
    if "ionic" in raw_str or "unknown" in raw_str:
        return None
    parts = raw_str.split('-')
    if len(parts) >= 2 and parts[0] == "mp":
        return f"mp-{parts[1]}"
    return raw_str

query_id = clean_mp_id(stable_entry_id)

# ---- 2c. Resolve fallback oxide if stable phase has no solid mp-id ----
with MPRester(MP_API_KEY) as mpr:
    if query_id is None:
        print(f"  [Warning] No solid mp-id; querying most stable oxide of {metal_symbol}.")
        results = mpr.summary.search(
            elements=[metal_symbol, "O"],
            fields=["material_id", "formula_pretty", "energy_above_hull"]
        )
        results_sorted = sorted(results, key=lambda x: x.energy_above_hull)
        query_id = results_sorted[0].material_id
        stable_formula = results_sorted[0].formula_pretty
        print(f"  [Fallback] Using: {stable_formula} ({query_id})")

print(f"  [Resolved] Material ID for DOS query: {query_id}")

# ---- 2d. DOS retrieval with retry + backoff (handles MP server timeouts) ----
def get_dos_with_retry(api_key, material_id, max_retries=4, base_delay=8):
    last_err = None
    for attempt in range(1, max_retries + 1):
        try:
            with MPRester(api_key) as mpr_retry:
                return mpr_retry.get_dos_by_material_id(material_id)
        except Exception as e:
            last_err = e
            wait = base_delay * attempt
            print(f"  [Retry {attempt}/{max_retries}] {type(e).__name__} — "
                  f"retrying in {wait}s...")
            time.sleep(wait)
    raise RuntimeError(
        f"DOS query for {material_id} failed after {max_retries} retries"
    ) from last_err

dos_data = get_dos_with_retry(MP_API_KEY, query_id)
print("  [Success] DOS data retrieved.")

# ---- 2e. Energy grid remap: align DFT E_F to E_F,active ----
efermi_dft   = dos_data.efermi
energies_raw = np.array(dos_data.energies)
energy_shift = E_F_active - efermi_dft
energies_abs = energies_raw + energy_shift

total_dos = np.array(dos_data.get_densities())

# ---- 2f. Extract Valence Band Maximum (VBM) ----
occupied_mask = energies_abs <= E_F_active
occ_E   = energies_abs[occupied_mask]
occ_dos = total_dos[occupied_mask]
threshold = 0.01 * np.max(total_dos)
vbm_candidates = occ_E[occ_dos > threshold]
E_VBM = float(vbm_candidates[-1]) if len(vbm_candidates) > 0 else E_F_active - 2.0
print(f"  E_VBM (vacuum scale) = {E_VBM:.4f} eV")

# ---- 2g. Robust PDOS extraction (metal d-band, O 2p-band) ----
def extract_orbital_dos(dos_obj, element_symbol, orbital_type):
    """
    Sum PDOS for a given element + orbital type across all spins/sites.
    Raises a visible warning (not a silent except) if nothing is found.
    """
    el = Element(element_symbol)
    pdos_sum = np.zeros(len(dos_obj.energies))
    found = False
    for site, site_dos in dos_obj.pdos.items():
        if site.specie == el:
            for orb, spin_dict in site_dos.items():
                if orb.orbital_type == orbital_type:
                    for spin, arr in spin_dict.items():
                        pdos_sum += np.array(arr)
                        found = True
    if not found:
        print(f"  [Warning] No {orbital_type} PDOS found for element '{element_symbol}'.")
    return pdos_sum

d_dos_raw = extract_orbital_dos(dos_data, metal_symbol, OrbitalType.d)

has_oxygen = "O" in stable_formula
if has_oxygen:
    p_dos_raw = extract_orbital_dos(dos_data, "O", OrbitalType.p)
else:
    p_dos_raw = np.zeros_like(d_dos_raw)
    print("  [Note] No oxygen in stable phase — O 2p PDOS set to zero.")

# ---- 2h. d-band center ----
occupied_d = d_dos_raw[occupied_mask]
if np.sum(occupied_d) > 1e-10:
    d_band_center = (np.trapezoid(occ_E * occupied_d, occ_E) /
                      np.trapezoid(occupied_d, occ_E))
else:
    d_band_center = E_VBM - 1.0
    print("  [Warning] d-band DOS near zero; using fallback estimate.")

print(f"  d-band center (ε_d, vacuum scale) = {d_band_center:.4f} eV")

# ============================================================
# 6. Quantum Descriptors & Selectivity Metrics
# ============================================================
print("\n" + "="*60)
print("STEP 3: Quantum Descriptors & Selectivity Index")
print("="*60)

def integrate_window(energies, dos_arr, E_low, E_high):
    mask = (energies >= E_low) & (energies <= E_high)
    if mask.sum() < 2: return 0.0
    return float(_trapz(dos_arr[mask], energies[mask]))

# E_F_active is now lower (more negative) on vacuum scale
delta_E_CH4   = E_F_active - E_HOMO_CH4
delta_E_CH3OH = E_F_active - E_HOMO_CH3OH

# Calculate and store individual integrals for the report
I_d_CH4 = integrate_window(energies_abs, d_dos_raw, E_HOMO_CH4, E_F_active)
I_p_CH4 = integrate_window(energies_abs, p_dos_raw, E_HOMO_CH4, E_F_active)
I_tot_CH4 = I_d_CH4 + I_p_CH4

I_d_CH3OH = integrate_window(energies_abs, d_dos_raw, E_HOMO_CH3OH, E_F_active)
I_p_CH3OH = integrate_window(energies_abs, p_dos_raw, E_HOMO_CH3OH, E_F_active)
I_tot_CH3OH = I_d_CH3OH + I_p_CH3OH

S_kinetic = I_tot_CH4 / (I_tot_CH3OH + 1e-20)

print(f"  ΔE_CH4: {delta_E_CH4:.3f} eV | ΔE_CH3OH: {delta_E_CH3OH:.3f} eV")
print(f"  Integrals (CH4): d={I_d_CH4:.4f}, p={I_p_CH4:.4f}")
print(f"  Selectivity Index S_kinetic: {S_kinetic:.4f}")
if S_kinetic > 1:
    print("    → SELECTIVE ✓")
else:
    print("    → NON-SELECTIVE ✗")

# ============================================================
# 7. OUTPUT: Clean Diagnostic Report + DataFrame
# ============================================================
print("\n" + "="*60)
print("DIAGNOSTIC REPORT SUMMARY")
print("="*60)

results_dict = {
    # Phase Diagnosis
    "Metal Symbol":               metal_symbol,
    "E_RHE (V)":                  E_RHE,
    "E_SHE (V)":                  round(E_SHE, 4),
    "pH":                         pH,
    "Temperature (K)":            temp_k,
    "Ion Concentration (mol/L)":  ion_conc,
    "Stable Phase Formula":       stable_formula,
    "mp-id":                      stable_entry_id,

    # Energy Alignment
    "E_F_active (eV)":            round(E_F_active, 4),
    "E_VBM (eV)":                 round(E_VBM, 4),
    "d-band center ε_d (eV)":     round(d_band_center, 4),
    "E_HOMO_CH4 (eV)":            E_HOMO_CH4,
    "E_HOMO_CH3OH (eV)":          E_HOMO_CH3OH,
    "ΔE_CH4 (eV)":                round(delta_E_CH4, 4),
    "ΔE_CH3OH (eV)":              round(delta_E_CH3OH, 4),

    # CH4 Activation Integrals
    "I_d_CH4 (states·eV)":        round(I_d_CH4, 4),
    "I_p_CH4 (states·eV)":        round(I_p_CH4, 4),
    "I_tot_CH4 (states·eV)":      round(I_tot_CH4, 4),

    # CH3OH Over-oxidation Integrals
    "I_d_CH3OH (states·eV)":      round(I_d_CH3OH, 4),
    "I_p_CH3OH (states·eV)":      round(I_p_CH3OH, 4),
    "I_tot_CH3OH (states·eV)":    round(I_tot_CH3OH, 4),

    # Selectivity
    "S_kinetic (I_CH4/I_CH3OH)":  round(S_kinetic, 4),
}

df_results = pd.DataFrame([results_dict]).T
df_results.columns = ["Value"]
print(df_results.to_string())
df_results.to_csv(f"screening_results_{metal_symbol}_pH{pH}_ERHE{E_RHE}.csv")
print(f"\n[Saved] screening_results_{metal_symbol}_pH{pH}_ERHE{E_RHE}.csv")

# ============================================================
# 8. VISUALIZATION: DOS Plot with Energy Windows
# ============================================================
fig, axes = plt.subplots(1, 2, figsize=(13, 5), sharey=True)
fig.suptitle(
    f"DOS Analysis: {stable_formula} ({metal_symbol}) | "
    f"E_RHE={E_RHE} V, pH={pH}, T={temp_k} K",
    fontsize=12, fontweight='bold'
)

for ax, window_lo, window_label, color_shade in zip(
        axes,
        [E_HOMO_CH4, E_HOMO_CH3OH],
        ["CH₄ Activation Window", "CH₃OH Over-oxidation Window"],
        ["#AED6F1", "#ABEBC6"]):

    ax.fill_between(energies_abs, d_dos_raw, alpha=0.75, color='steelblue', label=f"{metal_symbol} d-band")
    if has_oxygen:
        ax.fill_between(energies_abs, p_dos_raw, alpha=0.55, color='tomato', label="O 2p-band")
    ax.fill_betweenx(
        [0, max(total_dos) * 1.05],
        window_lo, E_F_active,
        alpha=0.25, color=color_shade, label=window_label
    )
    ax.axvline(E_F_active,  color='black',   lw=1.5, ls='--', label=f"E_F,active = {E_F_active:.2f} eV")
    ax.axvline(window_lo,   color='purple',  lw=1.2, ls=':',  label=f"E_HOMO = {window_lo} eV")
    ax.axvline(d_band_center, color='navy', lw=1.2, ls='-.', label=f"ε_d = {d_band_center:.2f} eV")
    ax.set_xlim([window_lo - 1.5, E_F_active + 1.0])
    ax.set_xlabel("Energy (eV vs. vacuum)", fontsize=11)
    ax.set_title(window_label, fontsize=10)
    ax.legend(fontsize=8, loc='upper left')
    ax.grid(alpha=0.3)

axes[0].set_ylabel("DOS (states/eV)", fontsize=11)
plt.tight_layout()
plt.savefig(f"dos_windows_{metal_symbol}.png", dpi=150)
plt.show()
print(f"[Saved] dos_windows_{metal_symbol}.png")

# ============================================================
# 9. MULTI-METAL SCREENING LOOP (optional extension)
# ============================================================
# Uncomment to screen multiple metals at once:

# metals_to_screen = ["Pt", "Ir", "Co", "Ni", "Cu", "Mn"]
# all_results = []
# for metal in metals_to_screen:
#     metal_symbol = metal
#     # Re-run Steps 1-3 here (wrap in a function for cleanliness)
#     # all_results.append(results_dict)
# df_all = pd.DataFrame(all_results)
# df_all.to_csv("multi_metal_screening.csv", index=False)